//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloodBanks2
    {
        public int BloodBankID { get; set; }
        public string BloodBankName { get; set; }
        public string BloodBankAddress { get; set; }
        public string BloodBankContactNumber { get; set; }
    }
}
