//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donors2
    {
        public int DonorID { get; set; }
        public string DonorName { get; set; }
        public string DonorBloodGroup { get; set; }
        public string DonorMedicalreport { get; set; }
        public string DonorAddress { get; set; }
        public string DonorContactInfo { get; set; }
    }
}
