//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BloodBank.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patients2
    {
        public int PatientID { get; set; }
        public string PatientName { get; set; }
        public string PatientBloodGroup { get; set; }
        public string PatientDisease { get; set; }
    }
}
